apiVersion: v1
kind: Service
metadata:
    name: "mytestaks-4e16"
    labels:
        app: "mytestaks-4e16"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "mytestaks-4e16"